CREATE OR REPLACE FUNCTION NAGF_PRECO_REFERENCIA(
    P_PRECO       IN NUMBER,
    P_MULTEQPEMB  IN NUMBER,
    P_UNIDADE     IN VARCHAR2
) RETURN NUMBER
IS
BEGIN
    RETURN CASE P_UNIDADE
             WHEN 'GR' THEN ROUND(P_PRECO / P_MULTEQPEMB * CASE WHEN P_MULTEQPEMB > 1 THEN 100 ELSE 0.1 END, 2)
             WHEN 'KG' THEN ROUND(P_PRECO / P_MULTEQPEMB, 2)
             WHEN 'MG' THEN ROUND(P_PRECO / P_MULTEQPEMB * CASE WHEN P_MULTEQPEMB > 1 THEN 100000 ELSE 0.0001 END, 2)
             WHEN 'ML' THEN ROUND(P_PRECO / P_MULTEQPEMB * 0.1, 2)
             WHEN 'LI' THEN ROUND(P_PRECO / P_MULTEQPEMB, 2)
             WHEN 'UN' THEN P_PRECO
           END;
END;
