CREATE OR REPLACE VIEW NAGV_BASE_PROD_SEAL AS

SELECT /*+ ORDERED */
       CASE WHEN BS.TIPO = 1 THEN 1
            WHEN BS.TIPO = 2 THEN CASE WHEN BS.PRECO_PROMOC < S.PRECOVALIDNORMAL THEN 2 ELSE 1 END
            WHEN BS.TIPO = 3 THEN CASE WHEN BS.PRECO_PROMOC < S.PRECOVALIDPROMOC AND S.PRECOVALIDPROMOC > 0 THEN 4 WHEN BS.PRECO_PROMOC < S.PRECOVALIDNORMAL THEN 3 END
            WHEN BS.TIPO = 4 THEN CASE WHEN BS.PRECO_PROMOC < S.PRECOVALIDPROMOC AND S.PRECOVALIDPROMOC > 0 THEN 6 WHEN BS.PRECO_PROMOC < S.PRECOVALIDNORMAL THEN 5 END
       ELSE 1 END
       TIPO,
       CASE WHEN BS.TIPO = 1 THEN 'Preco Padrao'
            WHEN BS.TIPO = 2 THEN CASE WHEN BS.PRECO_PROMOC < S.PRECOVALIDNORMAL THEN 'Oferta Tabloide' ELSE 'Preco Padrao' END
            WHEN BS.TIPO = 3 THEN CASE WHEN BS.PRECO_PROMOC < S.PRECOVALIDPROMOC AND S.PRECOVALIDPROMOC > 0 THEN 'Meu Nagumo + Oferta' WHEN BS.PRECO_PROMOC < S.PRECOVALIDNORMAL THEN 'Meu Nagumo' END
            WHEN BS.TIPO = 4 THEN CASE WHEN BS.PRECO_PROMOC < S.PRECOVALIDPROMOC AND S.PRECOVALIDPROMOC > 0 THEN 'Cartao Nagumo + Oferta' WHEN BS.PRECO_PROMOC < S.PRECOVALIDNORMAL THEN 'Cartao Nagumo' END
       ELSE 'Preco Padrao' END DESC_TIPO, 
       S.NROEMPRESA, S.SEQPRODUTO PLU, P.DESCCOMPLETA, S.PRECOVALIDNORMAL PRECO_NORMAL, S.PRECOVALIDPROMOC PRECO_2, 
       CASE WHEN BS.TIPO = 2 AND BS.PRECO_PROMOC < S.PRECOVALIDNORMAL THEN NULL ELSE BS.PRECO_PROMOC END PRECO_3, 
       BS.STATUS STATUS_PROMOC, NVL(BS.DTAALTERACAO, S.DTAALTERACAO) DTAALTERACAO, DTAINICIO, DTAFIM, 
       CASE WHEN E.MULTEQPEMB IS NOT NULL AND E.MULTEQPEMBALAGEM IS NOT NULL THEN 
       CASE WHEN E.MULTEQPEMBALAGEM = 'LI' THEN 'LITRO' WHEN  E.MULTEQPEMBALAGEM IN ('GR','MG') THEN '100g' WHEN E.MULTEQPEMBALAGEM = 'ML' THEN '100ml' ELSE E.MULTEQPEMBALAGEM END||' R$ '||
       TO_CHAR(CASE WHEN E.MULTEQPEMB IS NOT NULL OR E.MULTEQPEMBALAGEM IS NOT NULL THEN NAGF_PRECO_REFERENCIA(PRECOVALIDNORMAL, E.MULTEQPEMB, E.MULTEQPEMBALAGEM) END,'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') END INFO_EMB_1,
       CASE WHEN E.MULTEQPEMB IS NOT NULL AND E.MULTEQPEMBALAGEM IS NOT NULL AND PRECOVALIDPROMOC > 0 THEN 
       CASE WHEN E.MULTEQPEMBALAGEM = 'LI' THEN 'LITRO' WHEN  E.MULTEQPEMBALAGEM IN ('GR','MG') THEN '100g' WHEN E.MULTEQPEMBALAGEM = 'ML' THEN '100ml' ELSE E.MULTEQPEMBALAGEM END||' R$ '||
       TO_CHAR(CASE WHEN E.MULTEQPEMB IS NOT NULL OR E.MULTEQPEMBALAGEM IS NOT NULL THEN NAGF_PRECO_REFERENCIA(PRECOVALIDPROMOC, E.MULTEQPEMB, E.MULTEQPEMBALAGEM) END,'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') END INFO_EMB_2,
       CASE WHEN E.MULTEQPEMB IS NOT NULL AND E.MULTEQPEMBALAGEM IS NOT NULL AND BS.PRECO_PROMOC IS NOT NULL THEN 
       CASE WHEN E.MULTEQPEMBALAGEM = 'LI' THEN 'LITRO' WHEN  E.MULTEQPEMBALAGEM IN ('GR','MG') THEN '100g' WHEN E.MULTEQPEMBALAGEM = 'ML' THEN '100ml' ELSE E.MULTEQPEMBALAGEM END||' R$ '||
       TO_CHAR(CASE WHEN E.MULTEQPEMB IS NOT NULL OR E.MULTEQPEMBALAGEM IS NOT NULL THEN NAGF_PRECO_REFERENCIA(PRECO_PROMOC,     E.MULTEQPEMB, E.MULTEQPEMBALAGEM) END,'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') END INFO_EMB_3,
        ROW_NUMBER() OVER (
                   PARTITION BY NVL(BS.TIPO,1), S.NROEMPRESA
                   ORDER BY S.SEQPRODUTO
               ) RN
                                
  FROM MRL_PRODEMPSEG S INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = S.SEQPRODUTO
                        INNER JOIN MAP_FAMEMBALAGEM E ON E.SEQFAMILIA = P.SEQFAMILIA AND E.QTDEMBALAGEM = S.QTDEMBALAGEM
                        INNER JOIN MAX_EMPRESA M ON M.NROEMPRESA = S.NROEMPRESA AND M.NROSEGMENTOPRINC = S.NROSEGMENTO
                        LEFT JOIN (SELECT ROW_NUMBER() OVER (PARTITION BY X.SEQPRODUTO, X.NROEMPRESA ORDER BY X.PRECO_PROMOC ASC) ODR, X.* FROM NAGV_BASE_ALL_PROMO X) BS 
                               ON BS.SEQPRODUTO = S.SEQPRODUTO AND BS.NROEMPRESA = S.NROEMPRESA AND BS.PRECO_PROMOC <= NVL(NULLIF(PRECOVALIDPROMOC,0), PRECOVALIDNORMAL) AND ODR = 1

 WHERE 1=1
   AND S.PRECOVALIDNORMAL > 0
   AND S.QTDEMBALAGEM = 1
   AND S.STATUSVENDA = 'A'
