CREATE OR REPLACE VIEW NAGV_BASE_PROMOC_PDV_SEAL AS
SELECT DISTINCT X.SEQPROMOCPDV, DESCRICAO, DTAINICIO, DTAFIM, X.USUALTERACAO,
       XI.SEQPRODUTO, XD.PRECOPROMOCAO, XE.NROEMPRESA, XD.QTDAPARTIRDE, XI.QTDEMBALAGEM, X.TIPOPROMOCAO, INDTIPOQTDCARGAPDV, CODPARCEIRO, LPAD(XD.QTDAPARTIRDE,2,0)||
       CASE WHEN F.PESAVEL = 'S' THEN ' KG' ELSE ' UNID' END QTDE,
       CASE WHEN X.STATUS  = 'A'
             AND XI.STATUS = 'A'
             AND XE.STATUS = 'A'
             AND TRUNC(SYSDATE) BETWEEN X.DTAINICIO AND X.DTAFIM THEN 'A' ELSE 'I' END STATUS,
       -- Se a oferta saiu ontem, retorna a data de alteracao de hoje para receber a carga de saida
       GREATEST(CASE WHEN TRUNC(SYSDATE) > DTAFIM THEN TRUNC(SYSDATE) ELSE DATE '2000-01-01'END, X.DTAALTERACAO, XI.DTAALTERACAO) DTAALTERACAO
       
  FROM MFL_PROMOCAOPDV X INNER JOIN MFL_PROMOCPDVITEM XI ON XI.SEQPROMOCPDV = X.SEQPROMOCPDV -- MAPV_APIPROMOCAOAPARTIR
                         INNER JOIN MFL_PROMOCPDVDESCAPARTDE XD ON XD.SEQPROMOCPDV = X.SEQPROMOCPDV AND XD.SEQITEMPROMOC = XI.SEQITEMPROMOC
                         INNER JOIN MFL_PROMOCPDVEMP XE ON XE.SEQPROMOCPDV = X.SEQPROMOCPDV AND XE.NROEMPRESA = XD.NROEMPRESA
                         INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO
                         INNER JOIN MAP_FAMILIA F ON F.SEQFAMILIA = P.SEQFAMILIA

WHERE 1=1
  AND X.STATUS  = 'A'
  AND XI.STATUS = 'A'
  AND XE.STATUS = 'A'
  AND TRUNC(SYSDATE) BETWEEN X.DTAINICIO AND X.DTAFIM +1
   OR TRUNC(XI.DTAALTERACAO) = TRUNC(SYSDATE)
;
