CREATE OR REPLACE VIEW NAGV_PROMOC_ATIVAS_REGRAPDV_SEAL AS
SELECT A.SEQREGRA, A.DESCRICAO, A.TIPOREGRA, A.DTAINICIO, A.DTAFIM,
       B.SEQPRODUTO, B.PRECOBASE, B.PERCINCENTIVOPROD, B.PRECOINCENTIVOEMB, E.NROEMPRESA,
       CASE WHEN NVL(B.PERCINCENTIVOPROD,0) > 0 THEN ROUND(PRECOBASE - (PRECOBASE * PERCINCENTIVOPROD) / 100,2) ELSE PRECOINCENTIVOEMB END PRECO_FINAL,
       CASE WHEN TIPOREGRA = 'F'
   AND EXISTS (SELECT 1 FROM MAD_REGRAFORMAPAGTO F WHERE F.SEQREGRA = A.SEQREGRA AND F.NROFORMAPAGTO IN (92,93,24) AND F.STATUS = 'A' HAVING COUNT(NROFORMAPAGTO) = 3)
   AND E.STATUS = 'A'
   AND A.STATUS = 'A'
   AND B.STATUS = 'A'
   AND TRUNC(SYSDATE) BETWEEN A.DTAINICIO AND A.DTAFIM THEN 'A' ELSE 'I' END STATUS, 
   -- Se a oferta saiu ontem, retorna a data de alteracao de hoje para receber a carga de saida
  GREATEST(CASE WHEN TRUNC(SYSDATE) > A.DTAFIM THEN TRUNC(SYSDATE) ELSE DATE '2000-01-01' END,
           A.DTTALTERACAO, B.DTAALTPRECOBASE, E.DTAALTERACAO) DTAALTERACAO  
  FROM MFL_REGRAINCENTIVO A INNER JOIN MFL_REGRAPRODUTOPDV B ON A.SEQREGRA = B.SEQREGRA
                            INNER JOIN MAD_REGRAEMPRESA E ON E.SEQREGRA = A.SEQREGRA
 WHERE TIPOREGRA = 'F'
   AND EXISTS (SELECT 1 FROM MAD_REGRAFORMAPAGTO F WHERE F.SEQREGRA = A.SEQREGRA AND F.NROFORMAPAGTO IN (92,93,24) AND F.STATUS = 'A' HAVING COUNT(NROFORMAPAGTO) = 3)
   AND E.STATUS = 'A'
   AND A.STATUS = 'A'
   AND B.STATUS = 'A'
   AND TRUNC(SYSDATE) BETWEEN A.DTAINICIO AND A.DTAFIM +1;
